[package]
name = "speck_ex"
version = "0.1.0"
edition = "2021"

[lib]
name = "speck_ex"
crate-type = ["cdylib"]

[dependencies]
cipher = "0.5.0-rc.2"
ctr = "0.10.0-rc.2"
rustler = "0.37.1" # Check for latest version
speck-cipher = "0.1.0-rc.2"